[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "STADiffuser"
authors = [{name = "Chihao Zhang", email = "zhangchihao11@outlook.com"}]
dynamic = ["version", "description"]
